package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAssets<M extends BaseAssets<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setImageName(java.lang.String imageName) {
		set("image_name", imageName);
	}

	public java.lang.String getImageName() {
		return get("image_name");
	}

	public void setImageUrl(java.lang.String imageUrl) {
		set("image_url", imageUrl);
	}

	public java.lang.String getImageUrl() {
		return get("image_url");
	}

	public void setImageDesc(java.lang.String imageDesc) {
		set("image_desc", imageDesc);
	}

	public java.lang.String getImageDesc() {
		return get("image_desc");
	}

	public void setImageType(java.lang.String imageType) {
		set("image_type", imageType);
	}

	public java.lang.String getImageType() {
		return get("image_type");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

}
