package com.demo.common.model;

import com.demo.common.model.base.BaseAssets;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Assets extends BaseAssets<Assets> {
	public static final Assets dao = new Assets();
}
